#!/usr/bin/python3
# SPDX-FileCopyrighText: 2022 Aoi Ezawa
# SPDX-License-Identifier: BDS-3-Clasue

import sys

ans = 0
for line in sys.stdin:
    try:
         ans += int(line)
    except:
        ans += float(line)

print(ans)

